### ISSUE TITLE
Bind mount failed: '/etc/timezone' does not exists

### ISSUE THREAD

**Issue by TonySen1** [bilibili-koryking/1panel-docker#1]
大佬求救！！
使用1panel安装mysql报错提示对应映射目录不存在，手动建立对应目录后仍然报错
报错日志：Start container 1Panel-mysql-NG3b failed: {"message":"Bind mount failed: '/etc/timezone' does not exists"}

**Comment by bilibili-koryking** [comment]
来点截图看看，另外你这个是创建在哪里的？不行就自己手动改下mysql安装的compose配置文件把这一行删掉再试试

**Comment by TonySen1** [comment]
![Snipaste_2024-11-21_14-38-22](https://github.com/user-attachments/assets/3a96d889-8834-4bfb-ab6e-e1229b4138ce)
如图，用1panel安装mysql在群晖里显示错误就是这样

**Comment by TonySen1** [comment]
测试之后发现删掉那个挂载项就可以正常启动了，不知道这个挂载项重要不重要

**Comment by bilibili-koryking** [comment]
就是一个时区校准的，一般来说也没太大影响

**Comment by bilibili-koryking** [comment]
另外这个应该是查的你宿主机下的/etc/timezone而不是你链接的这个目录下的，你可以看看群晖自己的ssh下是不是有这个文件

**Comment by TonySen1** [comment]
宿主机里没这个文件

**Comment by bilibili-koryking** [comment]
问题就在这儿了，你先这么用吧，除了可能的mysql和宿主机时区不同步，应该也没啥问题，真有需要你也能手动去mysql后台自己改
